#配置数据源

spring:

  devtools:
    restart:
      enabled: false  #设置开启热部署
#      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  redis:
    host: 120.26.179.189
    port: 6379
    database: 0
    timeout: 10S
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000S
        min-idle: 1
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/whl?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      max-active: 20
      max-wait: 5000
      initial-size: 1

    #监控配置
file:
  staticAccessPath: /static/**
  uploadFolder: C:\workSpace\learnsys-parent\learnsys-admin\src\main\resources\static\video\
  uri: /upload/



learnsys:
  redis:
      open : true
server:
  port: 8888
  servlet:
    context-path: /learnsys

swagger:
  host: localhost:8888
  title: SpringBoot 整合 Swagger2
  description: 网站描述
  disabled: false # 是否禁用swagger
  redirect-uri: / # 禁用swagger时的重定向地址
project:
  version: 1.0
logging:
#  config: classpath:log4j2-local.xml

mybatis-plus:

  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mappers/**/*.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.whl.common.models.*

  #项目启动会检查xml配置存在(只在开发时候打开)
  check-config-location: true
  #SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句,REUSE：该执行器类型会复用预处理语句,BATCH：该执行器类型会批量执行所有的更新语句
#  default-executor-type: REUSE
#  #日志
#  log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false

    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jackson:
  time-zone: GMT+8
  date-format: yyyy-MM-dd HH:mm:ss
xhmm:
  push:
    name: aaa
